//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MentoHUST.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MENTOHUST_DIALOG            102
#define IDS_WELBOARD                    102
#define IDS_WELCOME                     103
#define IDS_RUIJIE_VERSION              104
#define IDS_EXITMSG                     105
#define IDS_NOTIFYMSG                   106
#define IDS_HELPERROR                   107
#define IDS_MSGCLEAR                    108
#define IDS_OUTPUT_D                    109
#define IDS_OUTPUT_U                    110
#define IDS_DISCONNECT                  111
#define IDS_BN_CONNECT                  112
#define IDS_BN_DISCONNECT               113
#define IDS_SERVERMSG                   114
#define IDS_ACCOUNT_CFG                 115
#define IDS_SYSTEM_CFG                  116
#define IDS_SAVE_SUCCESS                117
#define IDS_USERNAME                    118
#define IDS_PASSWORD                    119
#define IDS_IPADDRESS                   120
#define IDS_ACCOUNT_EMPTY               121
#define IDS_ACCOUNT_EXIST               122
#define IDS_INI_FILE                    123
#define IDS_LOGO_FILE                   124
#define IDS_WRITE_ERROR                 125
#define IDS_SETRUN_ERROR                126
#define IDS_PACKAGE_FILTER              127
#define IDR_MAINFRAME                   128
#define IDS_CANCEL                      128
#define IDI_CERTTING                    129
#define IDS_WNDCAPTION                  129
#define IDS_RUIJIE_ERG                  130
#define IDI_FAILED                      131
#define IDS_LINKURL                     131
#define IDB_LOGO                        132
#define IDS_LINKTIP                     132
#define IDS_FIND_NONIC                  133
#define IDS_NO_CLIENTCHECK              134
#define IDS_FILE_ERROR                  135
#define IDS_MD5_STRING                  136
#define IDD_CONFIGBOX                   137
#define IDS_OPEN_ERROR                  137
#define IDD_CFG_ACCOUNT                 138
#define IDS_LOCALMAC                    138
#define IDD_CFG_SYSTEM                  139
#define IDS_LOCALIP                     139
#define IDS_LOCALMASK                   140
#define IDR_TRAY_MENU                   141
#define IDS_LOCALGATE                   141
#define IDS_LOCALDNS                    142
#define IDS_USEIP                       143
#define IDS_SUCCESS                     144
#define IDS_FILTER_ERROR                145
#define IDS_DHCP_REMEW                  146
#define IDS_DHCP_TIMEOUT                147
#define IDS_DHCP_FAILED                 148
#define IDS_DHCP_END                    149
#define IDS_DHCP_RELEASE                150
#define IDS_TEXT_DISCONNECT             151
#define IDS_SEND_ERROR                  152
#define IDS_SERVER_ERROR                153
#define IDS_ID_ERROR                    154
#define IDS_MD5_ERROR                   155
#define IDS_TRAY_DISCONNECT             156
#define IDS_TRAY_DHCP                   157
#define IDS_TRAY_START                  158
#define IDS_TRAY_USERNAME               159
#define IDS_TRAY_PASSWORD               160
#define IDS_TRAY_SUCCESS                161
#define IDS_ARP_ALERT                   162
#define IDS_DESTMAC                     163
#define IDS_GATEMAC                     164
#define IDS_FAILURE                     165
#define IDS_FIND_SERVER                 166
#define IDS_SEND_NAME                   167
#define IDS_SEND_PASSWORD               168
#define IDS_SERVER_MSG                  169
#define IDS_CONTRACT                    170
#define IDS_TEXT_CONTRACT               171
#define IDC_BN_OUTPUT                   1000
#define IDC_BN_OPTION                   1001
#define IDC_SC_LOGO                     1002
#define IDC_CB_ADAPTER                  1003
#define IDC_CB_ACCOUNT                  1004
#define IDC_SC_STATE                    1005
#define IDC_ED_OUTPUT                   1007
#define IDC_BN_ABOUT                    1008
#define IDC_BN_HELP                     1009
#define IDC_BN_CLEAR                    1010
#define IDC_TAB                         1010
#define IDC_CK_AUTORUN                  1011
#define IDC_CK_AUTOCERT                 1012
#define IDC_CK_AUTOMIN                  1013
#define IDC_CK_BANDMAC                  1014
#define IDC_CB_DHCPMODE                 1016
#define IDC_ED_TIMEOUT                  1017
#define IDC_ED_USERNAME                 1017
#define IDC_ED_PASSWORD                 1018
#define IDC_ED_ECHOTIME                 1018
#define IDC_CB_STARTMODE                1019
#define IDC_CK_PACKAGE                  1022
#define IDC_BN_BROWSER                  1023
#define IDC_ED_PATH                     1025
#define IDC_LS_ACCOUNT                  1026
#define IDC_IPADDRESS                   1027
#define IDC_BN_ADD                      1028
#define IDC_BN_DEL                      1029
#define IDC_SC_CONTRACT                 1029
#define IDC_SC_CHECKNEW                 1030
#define ID_MENU_RESTORE                 32771
#define ID_MENU_CONNECT                 32772
#define ID_MENU_CONFIG                  32773
#define ID_MENU_HELP                    32774
#define ID_MENU_ABOUT                   32775
#define ID_MENU_EXIT                    32776

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         1031
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
